github.com:
    users:
        xuezhiorange-png:
            oauth_token: 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
    oauth_token: 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
    user: xuezhiorange-png
