"""Local filesystem artifact storage adapter.

Stores report export artifacts on the local filesystem with SHA-256
verification.  Storage keys are UUID-based and generated by the system
(not user-provided) to prevent path traversal.

Token+version fencing (P0-9):
- Every final artifact has a sidecar .meta file storing the owning
  claim's token and version.
- put() and delete() verify the caller's token+version match the
  file's sidecar metadata before allowing the operation.  Empty
  tokens do NOT bypass an existing owner.
- finalize_temp() writes the sidecar before moving the final file
  so a failure after the move never leaves an unowned artifact.
- replace() replaces an existing artifact via temp+atomic swap with
  backup/restore, preserving the original storage key.
- reclaim_delete() allows a new claim owner to clean up files from
  a stale claim by providing both the stale claim identifiers and
  the new reclaim identifiers.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from cold_storage.modules.reports.domain.errors import PathTraversalError
from cold_storage.modules.reports.domain.reclaim_delete_result import ReclaimDeleteResult


def _sanitize_file_name(file_name: str) -> str:
    """Sanitize file name: keep only alphanumeric, dash, underscore, dot."""
    # Remove path components
    base = os.path.basename(file_name)
    # Replace special characters with underscore
    sanitized = re.sub(r"[^a-zA-Z0-9._-]", "_", base)
    # Collapse multiple underscores
    sanitized = re.sub(r"_+", "_", sanitized)
    # Strip leading/trailing underscores and dots
    sanitized = sanitized.strip("_.")
    return sanitized or "artifact"


def _validate_storage_key(key: str) -> None:
    """Validate storage key has no path traversal characters."""
    if ".." in key or "/" in key or "\\" in key:
        raise PathTraversalError(key)
    if not key:
        raise PathTraversalError(key)


class ReportArtifactStorage:
    """Local filesystem artifact storage adapter.

    Parameters
    ----------
    base_dir:
        Root directory for artifact storage.  Created on init if missing.
    repository:
        Optional repository for startup recovery of pending outboxes.
    """

    def __init__(self, base_dir: str, repository: Any = None) -> None:
        self._base_dir = Path(base_dir)
        self._base_dir.mkdir(parents=True, exist_ok=True)
        self._recover_pending_deletes()
        # Run outbox recovery BEFORE incomplete-artifact cleanup so that
        # pending outbox deletions happen before legacy files (which lack
        # sidecars) get cleaned up as orphan payloads.
        if repository is not None:
            self._recover_pending_outboxes(repository)
        self._recover_incomplete_artifacts()

    # ------------------------------------------------------------------
    # Startup recovery
    # ------------------------------------------------------------------

    def _recover_pending_deletes(self) -> None:
        """Recover from crash during delete by cleaning pending_delete orphans.

        Scans the base directory for ``.pending_delete`` files and removes
        them completely.  Two-file pairs (payload + sidecar) are both removed;
        orphans (one file without its counterpart) are also removed.
        """
        # Collect all pending_delete files across all artifact dirs
        pending_files: list[Path] = []
        for entry in self._base_dir.iterdir():
            if entry.is_file() and entry.name.endswith(".pending_delete"):
                pending_files.append(entry)
            elif entry.is_dir():
                for f in entry.iterdir():
                    if f.is_file() and f.name.endswith(".pending_delete"):
                        pending_files.append(f)

        if not pending_files:
            return

        import logging

        logger = logging.getLogger(__name__)
        for pf in pending_files:
            try:
                pf.unlink()
                logger.info("Recovered pending_delete: %s", pf)
            except OSError as exc:
                logger.warning("Failed to remove pending_delete %s: %s", pf, exc)

    def _recover_incomplete_artifacts(self) -> None:
        """Recover from crashes during put/replace/finalize operations.

        Scans the storage directory and cleans up:
        - **Bundle tempdirs** — ``mkdtemp`` directories with ``payload`` +
          ``owner.json`` left behind after a crash in :meth:`put`, :meth:`replace`,
          or :meth:`finalize_temp`.
        - **Orphan sidecars** — ``.meta`` files whose matching payload
          file does not exist.
        - **Orphan payloads** — artifact files whose ``.meta`` sidecar
          does not exist.
        - **Broken JSON sidecars** — ``.meta`` files that cannot be parsed
          as valid JSON or contain a non-dict value.
        """
        import logging

        logger = logging.getLogger(__name__)

        # Phase 1: Clean up bundle tempdirs in base_dir
        for entry in list(self._base_dir.iterdir()):
            if (
                entry.is_dir()
                and (entry / "payload").is_file()
                and (entry / "owner.json").is_file()
            ):
                shutil.rmtree(entry, ignore_errors=True)
                logger.info("Recovered bundle tempdir: %s", entry)

        # Phase 2: Scan artifact directories for orphans and broken files
        EXCLUDED_SUFFIXES = (
            ".tmp",
            ".pending_delete",
            ".backup",
            ".meta.backup",
            ".reclaim_tmp",
            ".partial",
            ".quarantine",
        )

        for entry in list(self._base_dir.iterdir()):
            if not entry.is_dir() or not entry.exists():
                continue
            # Skip if this is (still) a bundle tempdir
            if (entry / "payload").is_file() and (entry / "owner.json").is_file():
                continue

            orphan_sidecars: list[Path] = []
            orphan_payloads: list[Path] = []
            broken_sidecars: list[Path] = []

            for f in entry.iterdir():
                if not f.is_file():
                    continue
                name = f.name
                # Skip temporary / control files
                if any(name.endswith(s) for s in EXCLUDED_SUFFIXES):
                    continue

                if name.endswith(".meta"):
                    # --- sidecar ---
                    # Check for broken JSON
                    try:
                        meta_data = json.loads(f.read_text())
                        if not isinstance(meta_data, dict):
                            raise ValueError("Not a dict")
                    except (json.JSONDecodeError, ValueError, OSError):
                        broken_sidecars.append(f)
                        continue
                    # Check for orphan sidecar (no matching payload)
                    payload_name = name[: -len(".meta")]
                    payload_path = entry / payload_name
                    if not payload_path.is_file():
                        orphan_sidecars.append(f)
                else:
                    # --- potential payload ---
                    meta_path = entry / (name + ".meta")
                    if not meta_path.is_file():
                        orphan_payloads.append(f)

            for f in broken_sidecars:
                f.unlink(missing_ok=True)
                logger.info("Recovered broken sidecar: %s", f)
            for f in orphan_sidecars:
                f.unlink(missing_ok=True)
                logger.info("Recovered orphan sidecar: %s", f)
            for f in orphan_payloads:
                f.unlink(missing_ok=True)
                logger.info("Recovered orphan payload: %s", f)

    def _recover_pending_outboxes(self, repository: Any) -> None:
        """Recover from crashes during delete_legacy_artifact (Part 2).

        Uses CAS claiming to safely process pending outboxes:

        1. Get eligible outboxes from ``repository.list_eligible_outboxes()``
        2. For each: CAS claim via ``repository.claim_deletion_outbox()``
        3. Only if claim succeeds: execute the file deletion
        4. On success: ``repository.complete_deletion_outbox()``
        5. On failure: ``repository.fail_deletion_outbox()``

        This is called from ``__init__`` when a *repository* is provided.
        """
        import logging
        from datetime import UTC, datetime

        logger = logging.getLogger(__name__)

        outboxes = repository.list_eligible_outboxes()
        for ob in outboxes:
            outbox_id = ob["id"]
            storage_key = ob["storage_key"]
            observed_status = ob["status"]
            observed_claim_version = ob.get("claim_version", 0)

            claim_token = f"recovery_{uuid.uuid4().hex[:8]}"

            # CAS claim the outbox
            if not repository.claim_deletion_outbox(
                outbox_id,
                claimant_token=claim_token,
                now=datetime.now(UTC),
                lease_seconds=60,
                observed_status=observed_status,
                observed_claim_version=observed_claim_version,
            ):
                # Another worker claimed it
                logger.debug(
                    "Recovery CAS claim failed for outbox %s (status=%s, cv=%d)",
                    outbox_id,
                    observed_status,
                    observed_claim_version,
                )
                continue

            # Claim succeeded — execute the file deletion
            repository.commit()
            file_path = self._find_artifact_path(storage_key)
            file_exists = file_path is not None and file_path.is_file()

            if file_exists:
                try:
                    pending_file = ReportArtifactStorage._pending_delete_path(
                        file_path  # type: ignore[arg-type]
                    )
                    file_path.rename(pending_file)  # type: ignore[union-attr]
                    pending_file.unlink(missing_ok=True)
                    repository.complete_deletion_outbox(
                        outbox_id,
                        claim_token=claim_token,
                        claim_version=observed_claim_version + 1,
                    )
                    repository.commit()
                    logger.info(
                        "Recovered outbox %s (sk=%s): file deleted",
                        outbox_id,
                        storage_key,
                    )
                except Exception as exc:
                    try:
                        repository.fail_deletion_outbox(
                            outbox_id,
                            claim_token=claim_token,
                            claim_version=observed_claim_version + 1,
                            error=str(exc),
                        )
                        repository.commit()
                    except Exception:
                        pass
                    logger.warning(
                        "Recovered outbox %s (sk=%s): deletion failed: %s",
                        outbox_id,
                        storage_key,
                        exc,
                    )
            else:
                # File already gone — mark as audited
                try:
                    repository.complete_deletion_outbox(
                        outbox_id,
                        claim_token=claim_token,
                        claim_version=observed_claim_version + 1,
                    )
                    repository.commit()
                    logger.info(
                        "Recovered outbox %s (sk=%s): file already missing",
                        outbox_id,
                        storage_key,
                    )
                except Exception as exc:
                    logger.warning(
                        "Recovered outbox %s (sk=%s): fail on missing: %s",
                        outbox_id,
                        storage_key,
                        exc,
                    )

    def _find_artifact_path(self, storage_key: str) -> Path | None:
        """Find an artifact file on disk by storage key (no sidecar required).

        Scans all subdirectories for a file whose name starts with the
        storage key.  Returns the Path or None if not found.
        """
        artifact_re = re.compile(r"^" + re.escape(storage_key) + r"_[A-Za-z0-9._-]+$")
        for artifact_dir in self._base_dir.iterdir():
            if artifact_dir.is_dir():
                for f in artifact_dir.iterdir():
                    if not f.is_file():
                        continue
                    if f.name.endswith(
                        (
                            ".meta",
                            ".meta.tmp",
                            ".reclaim_tmp",
                            ".pending_delete",
                            ".meta.pending_delete",
                            ".tmp",
                            ".partial",
                            ".backup",
                            ".meta.backup",
                            ".quarantine",
                        )
                    ):
                        continue
                    if artifact_re.match(f.name):
                        return f.resolve()
        return None

    # ------------------------------------------------------------------
    # Sidecar metadata (.meta) helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _meta_path(file_path: Path) -> Path:
        """Return the sidecar metadata path for a given artifact file.

        The sidecar is a JSON file with the same base name plus ``.meta``
        extension, placed in the same directory as the artifact file.
        """
        return file_path.with_name(file_path.name + ".meta")

    @staticmethod
    def _pending_delete_path(file_path: Path) -> Path:
        """Return the pending-delete path for a given artifact file.

        Renaming to a ``.pending_delete`` suffix makes deletions crash-safe:
        if the process crashes mid-delete, a cleanup pass can find and remove
        any files with this suffix.
        """
        return file_path.with_name(file_path.name + ".pending_delete")

    @staticmethod
    def _read_sidecar(meta_path: Path) -> dict[str, object] | None:
        """Read sidecar metadata from a .meta file.

        Returns the parsed JSON dict, or None if the file doesn't exist.
        """
        if meta_path.is_file():
            return json.loads(meta_path.read_text())  # type: ignore[no-any-return]
        return None

    @staticmethod
    def _write_sidecar(
        file_path: Path,
        *,
        artifact_id: str,
        storage_key: str,
        claim_token: str,
        claim_version: int,
    ) -> None:
        """Atomically write sidecar metadata next to an artifact file."""
        meta = {
            "artifact_id": artifact_id,
            "storage_key": storage_key,
            "claim_token": claim_token,
            "claim_version": claim_version,
        }
        meta_path = ReportArtifactStorage._meta_path(file_path)
        # Write to a temp file and rename for atomicity
        tmp = meta_path.with_suffix(meta_path.suffix + ".tmp")
        tmp.write_text(json.dumps(meta, sort_keys=True))
        # fsync temp file before rename to ensure data is on disk
        with open(tmp, "rb") as f:
            os.fsync(f.fileno())
        tmp.replace(str(meta_path))
        # fsync parent directory to persist the rename
        dir_fd = os.open(str(meta_path.parent), os.O_RDONLY)
        try:
            os.fsync(dir_fd)
        finally:
            os.close(dir_fd)

    @staticmethod
    def _check_fencing_for_meta(
        meta: dict[str, object] | None,
        storage_key: str,
        claim_token: str,
        claim_version: int,
        *,
        legacy_ok: bool = False,
    ) -> None:
        """Check token+version fencing against loaded sidecar metadata.

        Parameters
        ----------
        meta:
            Parsed sidecar data, or None for legacy files (no .meta).
        storage_key:
            Storage key for error messages.
        claim_token:
            Token provided by the caller.
        claim_version:
            Version provided by the caller.
        legacy_ok:
            If True, legacy files (no sidecar) are allowed without error.
            Default False: legacy files raise ``PermissionError``.

        Raises
        ------
        PermissionError
            If sidecar exists but claim_token or claim_version don't match,
            or if no sidecar exists and legacy_ok is False.
            An empty token does NOT bypass an existing owner.
        """
        if meta is None:
            if legacy_ok:
                return
            raise PermissionError(
                f"Storage key {storage_key} has no owner metadata (legacy file). "
                f"Use delete_legacy_artifact() for privileged migration delete."
            )
        stored_token = meta.get("claim_token", "")
        stored_version = meta.get("claim_version", 0)
        if stored_token != claim_token or stored_version != claim_version:
            raise PermissionError(
                f"Storage key {storage_key} fencing mismatch: "
                f"stored token={stored_token!r} version={stored_version}, "
                f"provided token={claim_token!r} version={claim_version}"
            )

    # ------------------------------------------------------------------
    # _publish_bundle -- shared atomic publish primitive
    # ------------------------------------------------------------------

    def _publish_bundle(
        self,
        data: bytes,
        *,
        artifact_id: str,
        storage_key: str,
        final_path: Path,
        claim_token: str,
        claim_version: int,
    ) -> None:
        """Atomically publish a payload + metadata sidecar bundle.

        This is the shared primitive used by both :meth:`put` and
        :meth:`finalize_temp`.  It writes the payload and its sidecar
        to a temporary directory, fsyncs both files and the directory,
        verifies the SHA-256 hash, and then atomically renames them into
        place (meta first, then payload).

        Parameters
        ----------
        data:
            Raw file bytes to store.
        artifact_id:
            The artifact UUID (used for directory structure).
        storage_key:
            The UUID-based storage key for the final file name.
        final_path:
            The final absolute path for the payload file.
        claim_token:
            Token of the owning claim.
        claim_version:
            Version of the owning claim.

        Raises
        ------
        ValueError
            If SHA-256 verification fails.
        """
        bundle_tmp = Path(tempfile.mkdtemp(dir=str(self._base_dir), prefix=f"{storage_key}_"))
        try:
            payload_tmp = bundle_tmp / "payload"
            meta_tmp = bundle_tmp / "owner.json"
            payload_tmp.write_bytes(data)
            meta_tmp.write_text(
                json.dumps(
                    {
                        "artifact_id": artifact_id,
                        "storage_key": storage_key,
                        "claim_token": claim_token,
                        "claim_version": claim_version,
                    },
                    sort_keys=True,
                )
            )
            # fsync both files
            for p in (payload_tmp, meta_tmp):
                with open(p, "rb") as f:
                    os.fsync(f.fileno())
            # fsync bundle directory
            dir_fd = os.open(str(bundle_tmp), os.O_RDONLY)
            try:
                os.fsync(dir_fd)
            finally:
                os.close(dir_fd)

            # Verify SHA-256 before publishing
            actual_hash = self._compute_sha256(payload_tmp)
            expected_hash = hashlib.sha256(data).hexdigest()
            if actual_hash != expected_hash:
                raise ValueError(
                    f"SHA-256 verification failed: expected {expected_hash}, got {actual_hash}"
                )

            # Atomic rename: meta first, then payload
            # By renaming meta BEFORE payload, a crash between the two
            # leaves a non-functional orphan sidecar (no payload) rather
            # than a payload without an owner.
            meta_path = ReportArtifactStorage._meta_path(final_path)
            meta_tmp.rename(str(meta_path))
            payload_tmp.rename(final_path)
            # fsync parent directory
            parent_fd = os.open(str(final_path.parent), os.O_RDONLY)
            try:
                os.fsync(parent_fd)
            finally:
                os.close(parent_fd)
        finally:
            # Clean up temp bundle directory if anything remains
            if bundle_tmp.is_dir():
                shutil.rmtree(bundle_tmp, ignore_errors=True)

    # ------------------------------------------------------------------
    # Core operations
    # ------------------------------------------------------------------

    def put(
        self,
        artifact_id: str,
        data: bytes,
        file_name: str,
        *,
        claim_token: str = "",
        claim_version: int = 0,
    ) -> str:
        """Store artifact data and return a storage key.

        Parameters
        ----------
        artifact_id:
            The artifact UUID (used for directory structure).
        data:
            Raw file bytes to store.
        file_name:
            Original file name (will be sanitized).
        claim_token:
            Token of the owning claim.  Used for fencing if the key exists.
        claim_version:
            Version of the owning claim.

        Returns
        -------
        str
            Storage key (UUID-based) for later retrieval.

        Raises
        ------
        ValueError
            If data is empty or file_name is invalid after sanitization.
        PermissionError
            If the storage key already exists and is owned by a different
            claim token+version.
        """
        if not data:
            raise ValueError("Artifact data must not be empty")

        storage_key = str(uuid.uuid4())
        safe_name = _sanitize_file_name(file_name)
        artifact_dir = self._base_dir / artifact_id
        artifact_dir.mkdir(parents=True, exist_ok=True)
        final_path = artifact_dir / f"{storage_key}_{safe_name}"

        self._publish_bundle(
            data,
            artifact_id=artifact_id,
            storage_key=storage_key,
            final_path=final_path,
            claim_token=claim_token,
            claim_version=claim_version,
        )

        return storage_key

    def get(self, storage_key: str) -> bytes:
        """Retrieve artifact data by storage key.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.

        Returns
        -------
        bytes
            The raw file content.

        Raises
        ------
        FileNotFoundError
            If the artifact does not exist.
        """
        path = self.get_path(storage_key)
        return Path(path).read_bytes()

    def exists(self, storage_key: str) -> bool:
        """Check if an artifact exists.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.

        Returns
        -------
        bool
            True if the artifact file exists.
        """
        try:
            path = self.get_path(storage_key)
            return Path(path).is_file()
        except (PathTraversalError, FileNotFoundError):
            return False

    def delete(
        self,
        storage_key: str,
        *,
        claim_token: str = "",
        claim_version: int = 0,
    ) -> None:
        """Delete an artifact.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.
        claim_token:
            Token of the owning claim (used for fencing).
        claim_version:
            Version of the owning claim.

        Raises
        ------
        FileNotFoundError
            If the artifact does not exist.
        PermissionError
            If the sidecar metadata exists and the claim_token/version
            don't match.  Empty token does NOT bypass an existing owner.
        """
        path = self.get_path(storage_key)
        file_path = Path(path)
        if not file_path.is_file():
            raise FileNotFoundError(f"Artifact not found: {storage_key}")

        meta_path = ReportArtifactStorage._meta_path(file_path)
        meta = ReportArtifactStorage._read_sidecar(meta_path)
        ReportArtifactStorage._check_fencing_for_meta(
            meta,
            storage_key,
            claim_token,
            claim_version,
        )

        # Crash-safe deletion: rename file+meta to .pending_delete,
        # then unlink both. If we crash between the renames, a
        # dedicated cleanup pass picks up stale .pending_delete files.
        pending_file = ReportArtifactStorage._pending_delete_path(file_path)
        pending_meta = ReportArtifactStorage._pending_delete_path(meta_path)
        file_path.rename(pending_file)
        if meta_path.is_file():
            meta_path.rename(pending_meta)
        pending_file.unlink(missing_ok=True)
        pending_meta.unlink(missing_ok=True)

    def replace(
        self,
        storage_key: str,
        data: bytes,
        *,
        claim_token: str = "",
        claim_version: int = 0,
    ) -> str:
        """Replace an existing artifact's content in-place (temp+atomic swap).

        Overwrites the file identified by *storage_key* with new *data*
        after validating that the caller owns the artifact (token+version
        fencing).  The storage key stays the same; the sidecar metadata
        is updated with the new claim credentials while preserving the
        original ``artifact_id``.

        The operation follows this sequence:
        1. Validate fencing and non-empty data
        2. Write new payload + metadata to a temp bundle directory
        3. Fsync both files and the temp directory
        4. Compute and verify the SHA-256 hash
        5. Rename old files to ``.backup`` / ``.meta.backup``
        6. Atomically rename new meta then payload into place
        7. Fsync the parent directory
        8. Remove the backups
        9. On any failure after step 5, restore from backups

        Parameters
        ----------
        storage_key:
            The UUID-based storage key of the existing artifact.
        data:
            Raw file bytes to write.
        claim_token:
            Token of the owning claim (used for fencing).
        claim_version:
            Version of the owning claim.

        Returns
        -------
        str
            The same *storage_key* on success.

        Raises
        ------
        FileNotFoundError
            If the artifact does not exist.
        PermissionError
            If the sidecar metadata exists and the claim_token/version
            don't match.
        ValueError
            If *data* is empty.
        """
        if not data:
            raise ValueError("Artifact data must not be empty")

        path = self.get_path(storage_key)
        file_path = Path(path)

        # Validate fencing before touching the file
        meta_path = ReportArtifactStorage._meta_path(file_path)
        meta = ReportArtifactStorage._read_sidecar(meta_path)
        ReportArtifactStorage._check_fencing_for_meta(
            meta,
            storage_key,
            claim_token,
            claim_version,
        )

        # Preserve original artifact_id from existing metadata
        artifact_id: str = ""
        if meta is not None:
            artifact_id = str(meta.get("artifact_id", ""))

        # --- Step 2-4: Write new payload + meta to temp bundle ---
        bundle_tmp = Path(tempfile.mkdtemp(dir=str(self._base_dir), prefix=f"{storage_key}_"))
        try:
            payload_tmp = bundle_tmp / "payload"
            meta_tmp = bundle_tmp / "owner.json"
            payload_tmp.write_bytes(data)
            meta_tmp.write_text(
                json.dumps(
                    {
                        "artifact_id": artifact_id,
                        "storage_key": storage_key,
                        "claim_token": claim_token,
                        "claim_version": claim_version,
                    },
                    sort_keys=True,
                )
            )
            # Fsync both files
            for p in (payload_tmp, meta_tmp):
                with open(p, "rb") as f:
                    os.fsync(f.fileno())
            # Fsync bundle directory
            dir_fd = os.open(str(bundle_tmp), os.O_RDONLY)
            try:
                os.fsync(dir_fd)
            finally:
                os.close(dir_fd)

            # SHA-256 verification
            actual_hash = self._compute_sha256(payload_tmp)
            expected_hash = hashlib.sha256(data).hexdigest()
            if actual_hash != expected_hash:
                raise ValueError(
                    f"SHA-256 verification failed: expected {expected_hash}, got {actual_hash}"
                )

            # --- Step 5: Backup old files ---
            payload_backup = file_path.with_name(file_path.name + ".backup")
            meta_backup = meta_path.with_name(meta_path.name + ".backup")
            file_path.rename(payload_backup)
            if meta_path.is_file():
                meta_path.rename(meta_backup)

            try:
                # --- Step 6: Atomic rename (meta first, then payload) ---
                meta_tmp.rename(str(meta_path))
                payload_tmp.rename(str(file_path))

                # --- Step 7: Fsync parent directory ---
                parent_fd = os.open(str(file_path.parent), os.O_RDONLY)
                try:
                    os.fsync(parent_fd)
                finally:
                    os.close(parent_fd)

                # --- Step 8: Remove backups ---
                payload_backup.unlink(missing_ok=True)
                meta_backup.unlink(missing_ok=True)
            except Exception:
                # --- Step 9: Restore from backup on failure ---
                if not file_path.is_file() and payload_backup.exists():
                    payload_backup.rename(str(file_path))
                if not meta_path.is_file() and meta_backup.exists():
                    meta_backup.rename(str(meta_path))
                raise
        finally:
            # Clean up temp bundle directory if anything remains
            if bundle_tmp.is_dir():
                shutil.rmtree(bundle_tmp, ignore_errors=True)

        return storage_key

    def reclaim_delete(
        self,
        storage_key: str,
        *,
        stale_claim_token: str,
        stale_claim_version: int,
        reclaim_token: str = "",
        reclaim_version: int = 0,
        missing_is_success: bool = False,
        repository: Any = None,
    ) -> ReclaimDeleteResult:
        """Delete an artifact using reclaim credentials (two-phase protocol).

        Like delete(), but accepts *stale* claim identifiers to match
        against the file's sidecar metadata.  This allows the new owner
        of a claim (identified by *reclaim_token* / *reclaim_version*) to
        clean up files that were created under the old (stale) owner.

        The reclaim_token and reclaim_version are recorded in the sidecar
        metadata before deletion for audit-trail purposes.

        Two-phase protocol (when *repository* is provided):

        1. **Phase 1 (intent)**: Insert a ``DeletionReceiptRecord`` with
           ``status='intent'`` and commit it.  This proves the intention
           to delete.
        2. **Phase 2 (delete)**: Perform the actual file deletion.
        3. **Phase 3 (complete)**: Update the receipt to ``status='deleted'``
           and commit again.

        If Phase 2 fails, the receipt is updated to ``delete_failed``.

        When *missing_is_success* is True, a valid *repository* is required
        so that the ``DeletionReceiptRecord`` can be verified.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.
        stale_claim_token:
            Token of the old (stale) claim that owned this file.
        stale_claim_version:
            Version of the old (stale) claim.
        reclaim_token:
            Token of the new claim doing the cleanup (for audit).
        reclaim_version:
            Version of the new claim.
        missing_is_success:
            If True and the file does not exist, check for a matching
            *DeletionReceiptRecord*.  If the receipt matches all four
            claim identifiers return ``already_missing``.  Without a
            matching receipt the operation fails closed.
        repository:
            Required when *missing_is_success* is True.  Otherwise
            optional (backward compat without receipt verification).

        Returns
        -------
        ReclaimDeleteResult
            ``status="deleted"`` if the file was actually removed.
            ``status="already_missing"`` if *missing_is_success* is True
            and a matching deletion receipt exists.

        Raises
        ------
        ValueError
            If *missing_is_success* is True and *repository* is None.
        FileNotFoundError
            If the artifact does not exist and *missing_is_success* is
            False, or if the file is missing but no receipt exists.
        PermissionError
            If the sidecar metadata exists and its token/version don't
            match the stale_claim_token/stale_claim_version, or if the
            file is missing and the existing receipt claims ownership
            by a different set of identifiers.
        """
        # Validate that missing_is_success requires a repository
        if missing_is_success and repository is None:
            raise ValueError(
                "missing_is_success=True requires a valid repository "
                "for DeletionReceipt verification"
            )

        # Check if file exists
        try:
            path = self.get_path(storage_key)
            file_path = Path(path)
            file_exists = file_path.is_file()
        except FileNotFoundError:
            file_exists = False

        if not file_exists:
            # File is missing
            if missing_is_success:
                return self._handle_missing_with_receipt(
                    storage_key,
                    stale_claim_token=stale_claim_token,
                    stale_claim_version=stale_claim_version,
                    reclaim_token=reclaim_token,
                    reclaim_version=reclaim_version,
                    repository=repository,
                )
            raise FileNotFoundError(f"Artifact not found: {storage_key}")

        meta_path = ReportArtifactStorage._meta_path(file_path)
        meta = ReportArtifactStorage._read_sidecar(meta_path)

        if meta is not None:
            stored_token = meta.get("claim_token", "")
            stored_version = meta.get("claim_version", 0)
            if stored_token != stale_claim_token or stored_version != stale_claim_version:
                raise PermissionError(
                    f"Reclaim delete fencing mismatch for {storage_key}: "
                    f"stored token={stored_token!r} version={stored_version}, "
                    f"stale token={stale_claim_token!r} version={stale_claim_version}"
                )
            # Record reclaim metadata before deleting (audit trail)
            reclaimed_meta = dict(meta)
            reclaimed_meta["reclaimed_by_token"] = reclaim_token
            reclaimed_meta["reclaimed_by_version"] = reclaim_version
            tmp = meta_path.with_suffix(meta_path.suffix + ".reclaim_tmp")
            tmp.write_text(json.dumps(reclaimed_meta, sort_keys=True))
            tmp.replace(str(meta_path))

        # Compute deletion hash before deleting
        deletion_hash = self._compute_sha256(file_path) if file_path.is_file() else ""

        # Phase 1: Insert intent receipt and commit
        if repository is not None:
            repository.insert_deletion_receipt(
                storage_key=storage_key,
                stale_claim_token=stale_claim_token,
                stale_claim_version=stale_claim_version,
                reclaim_token=reclaim_token,
                reclaim_version=reclaim_version,
                deletion_hash=deletion_hash,
                status="intent",
                deleted_at=None,
            )
            repository.commit()

        # Phase 2: Perform crash-safe file deletion
        try:
            pending_file = ReportArtifactStorage._pending_delete_path(file_path)
            pending_meta = ReportArtifactStorage._pending_delete_path(meta_path)
            file_path.rename(pending_file)
            if meta_path.is_file():
                meta_path.rename(pending_meta)
            pending_file.unlink(missing_ok=True)
            pending_meta.unlink(missing_ok=True)
        except Exception:
            # Phase 2 failed -- update receipt to delete_failed
            if repository is not None:
                try:
                    repository.update_deletion_receipt_status(
                        storage_key, "delete_failed", deleted_at=None
                    )
                    repository.commit()
                except Exception:
                    pass
            raise

        # Phase 3: Update receipt to 'deleted' and commit
        if repository is not None:
            repository.update_deletion_receipt_status(
                storage_key,
                "deleted",
                deleted_at=datetime.now(UTC),
            )
            repository.commit()

        return ReclaimDeleteResult(status="deleted", storage_key=storage_key)

    def _handle_missing_with_receipt(
        self,
        storage_key: str,
        *,
        stale_claim_token: str,
        stale_claim_version: int,
        reclaim_token: str,
        reclaim_version: int,
        repository: Any = None,
    ) -> ReclaimDeleteResult:
        """Handle the ``already_missing`` path with receipt verification.

        Two-phase aware:

        - **No receipt** -> raise ``FileNotFoundError``.
        - **Receipt exists, status='intent', file missing** -> the
          previous run crashed after Phase 1 but before Phase 2.  We
          have already confirmed the file is missing; update receipt
          to ``deleted`` and return ``already_missing``.
        - **Receipt exists, status='deleted', owner matches** ->
          return ``already_missing``.
        - **Receipt exists but owner mismatches** -> raise
          ``PermissionError``.
        """
        receipt = repository.get_deletion_receipt(storage_key)
        if receipt is None:
            raise FileNotFoundError(
                f"Artifact not found and no deletion receipt: {storage_key}. "
                f"Cannot treat as already_missing without proof of prior deletion."
            )

        # All four claim identifiers must match
        if (
            receipt["stale_claim_token"] != stale_claim_token
            or receipt["stale_claim_version"] != stale_claim_version
            or receipt["reclaim_token"] != reclaim_token
            or receipt["reclaim_version"] != reclaim_version
        ):
            raise PermissionError(
                f"Reclaim delete receipt mismatch for {storage_key}: "
                f"receipt has stale_token={receipt['stale_claim_token']!r} "
                f"stale_version={receipt['stale_claim_version']} "
                f"reclaim_token={receipt['reclaim_token']!r} "
                f"reclaim_version={receipt['reclaim_version']}, "
                f"provided stale_token={stale_claim_token!r} "
                f"stale_version={stale_claim_version} "
                f"reclaim_token={reclaim_token!r} "
                f"reclaim_version={reclaim_version}"
            )

        # If status is 'intent' and file is missing, the previous run
        # crashed after Phase 1 (intent committed) but before Phase 2
        # (file deletion).  The file is confirmed gone (we already
        # checked), so transition to 'deleted'.
        if receipt.get("status") == "intent":
            repository.update_deletion_receipt_status(
                storage_key,
                "deleted",
                deleted_at=datetime.now(UTC),
            )
            repository.commit()

        return ReclaimDeleteResult(status="already_missing", storage_key=storage_key)

    def get_path(self, storage_key: str) -> str:
        """Get the absolute path for an artifact.

        Validates that the sidecar metadata file exists, is valid JSON,
        and that the ``storage_key`` inside the metadata matches the
        requested key.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.

        Returns
        -------
        str
            Absolute file path.

        Raises
        ------
        PathTraversalError
            If the storage key contains traversal characters.
        FileNotFoundError
            If the artifact does not exist, the sidecar is missing,
            the sidecar cannot be parsed, or the sidecar's storage_key
            does not match.
        """
        _validate_storage_key(storage_key)

        # Use a strict regex to match only final artifact files.
        # Exclude: .meta, .meta.tmp, .reclaim_tmp, .pending_delete,
        # .meta.pending_delete, .tmp, partial, .backup, .meta.backup, quarantine
        artifact_re = re.compile(r"^" + re.escape(storage_key) + r"_[A-Za-z0-9._-]+$")
        exclude_suffixes = (
            ".meta",
            ".meta.tmp",
            ".reclaim_tmp",
            ".pending_delete",
            ".meta.pending_delete",
            ".tmp",
            ".partial",
            ".backup",
            ".meta.backup",
            ".quarantine",
        )

        for artifact_dir in self._base_dir.iterdir():
            if artifact_dir.is_dir():
                for file in artifact_dir.iterdir():
                    if not file.is_file():
                        continue
                    name = file.name
                    # Skip any excluded suffix
                    if name.endswith(exclude_suffixes):
                        continue
                    # Must match the strict artifact pattern
                    if artifact_re.match(name):
                        file_path = file.resolve()

                        # Validate sidecar: exists + parseable + storage_key match
                        meta_path = ReportArtifactStorage._meta_path(Path(file_path))
                        if not meta_path.is_file():
                            raise FileNotFoundError(
                                f"Artifact {storage_key} has no sidecar metadata file "
                                f"(missing {meta_path.name})"
                            )
                        try:
                            meta_data = json.loads(meta_path.read_text())
                            if not isinstance(meta_data, dict):
                                raise ValueError("Sidecar content is not a JSON object")
                        except (json.JSONDecodeError, ValueError, OSError) as exc:
                            raise FileNotFoundError(
                                f"Artifact {storage_key} has unreadable sidecar metadata: {exc}"
                            ) from exc

                        stored_key = meta_data.get("storage_key", "")
                        if stored_key != storage_key:
                            raise FileNotFoundError(
                                f"Artifact {storage_key} storage key mismatch in sidecar: "
                                f"expected {storage_key}, got {stored_key}"
                            )

                        return str(file_path)

        raise FileNotFoundError(f"Artifact not found: {storage_key}")

    @staticmethod
    def _compute_sha256(file_path: Path) -> str:
        """Compute SHA-256 hash of a file."""
        sha256 = hashlib.sha256()
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                sha256.update(chunk)
        return sha256.hexdigest()

    # ------------------------------------------------------------------
    # P0-7: Temp file methods for atomic artifact writes
    # ------------------------------------------------------------------

    def put_temp(self, data: bytes, file_name: str) -> tuple[str, str]:
        """Write data to a temp file and return (temp_path, sha256).

        The temp file is created in the base_dir for easy cleanup.
        SHA-256 is computed and returned alongside the path.

        Parameters
        ----------
        data:
            Raw file bytes to store.
        file_name:
            Original file name (used for temp file suffix).

        Returns
        -------
        tuple[str, str]
            (temp_file_path, sha256_hex_digest)

        Raises
        ------
        ValueError
            If data is empty.
        """
        if not data:
            raise ValueError("Artifact data must not be empty")

        safe_name = _sanitize_file_name(file_name)
        # Create a unique temp file in the base directory
        fd, temp_path = tempfile.mkstemp(
            suffix=f"_{safe_name}",
            prefix="art_",
            dir=str(self._base_dir),
        )
        try:
            os.write(fd, data)
        finally:
            os.close(fd)

        # Verify SHA-256
        sha256_hash = self._compute_sha256(Path(temp_path))

        return temp_path, sha256_hash

    def finalize_temp(
        self,
        temp_path: str,
        artifact_id: str,
        file_name: str,
        *,
        claim_token: str = "",
        claim_version: int = 0,
    ) -> str:
        """Move temp file to final artifact location and write sidecar metadata.

        Uses :meth:`_publish_bundle` to atomically publish the payload and
        sidecar, ensuring that a crash never leaves an unowned artifact.

        Parameters
        ----------
        temp_path:
            Path to the temp file (from put_temp).
        artifact_id:
            The artifact UUID (used for directory structure).
        file_name:
            Original file name (will be sanitized).
        claim_token:
            Token of the owning claim (stored in sidecar metadata).
        claim_version:
            Version of the owning claim.

        Returns
        -------
        str
            Storage key (UUID-based) for later retrieval.

        Raises
        ------
        FileNotFoundError
            If the temp file does not exist.
        ValueError
            If the temp file is empty.
        """
        temp = Path(temp_path)
        if not temp.is_file():
            raise FileNotFoundError(f"Temp file not found: {temp_path}")

        file_size = temp.stat().st_size
        if file_size == 0:
            raise ValueError("Temp file is empty")

        storage_key = str(uuid.uuid4())
        safe_name = _sanitize_file_name(file_name)
        artifact_dir = self._base_dir / artifact_id
        artifact_dir.mkdir(parents=True, exist_ok=True)
        final_path = artifact_dir / f"{storage_key}_{safe_name}"

        # Read temp file bytes
        data = temp.read_bytes()

        # Atomically publish using the shared bundle primitive
        self._publish_bundle(
            data,
            artifact_id=artifact_id,
            storage_key=storage_key,
            final_path=final_path,
            claim_token=claim_token,
            claim_version=claim_version,
        )

        # Clean up the temp file now that we've published successfully
        temp.unlink(missing_ok=True)

        return storage_key

    def delete_legacy_artifact(
        self,
        storage_key: str,
        *,
        migration_actor: str,
        audit_reason: str,
        repository: Any,  # REQUIRED -- no default, no fallback to _write_audit_log
    ) -> None:
        """Privileged migration delete for legacy artifacts without owner metadata.

        Only callable by a migration/audit path, not by normal render/reclaim.
        Requires an explicit actor identity and reason for audit trail.

        Uses a transactional outbox pattern to ensure the audit record is
        committed BEFORE the file deletion:

        1. Insert ``DeletionOutboxRecord`` (status ``pending_audit``)
        2. ``repository.commit()`` -- audit is durable before file delete
        3. Perform crash-safe file deletion (quarantine + rename)
        4. Update outbox status to ``audited``
        5. ``repository.commit()`` again
        6. If file deletion fails: update status to ``delete_failed``,
           commit, then re-raise the exception.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.
        migration_actor:
            Identity of the user/process performing the migration delete.
        audit_reason:
            Reason for the privileged delete.
        repository:
            Repository instance used for outbox persistence.  REQUIRED.

        Raises
        ------
        ValueError
            If *migration_actor* or *audit_reason* are blank (or whitespace only).
        FileNotFoundError
            If the artifact does not exist.
        PermissionError
            If the file HAS a sidecar (use normal delete instead).
        """
        # Validate actor and reason are non-blank
        if not (migration_actor.strip() and audit_reason.strip()):
            raise ValueError("migration_actor and audit_reason must be non-empty strings")

        # Use direct file discovery (not get_path) because legacy files
        # lack sidecars, and get_path now validates sidecar existence.
        _validate_storage_key(storage_key)
        artifact_re = re.compile(r"^" + re.escape(storage_key) + r"_[A-Za-z0-9._-]+$")

        file_path: Path | None = None
        for artifact_dir in self._base_dir.iterdir():
            if artifact_dir.is_dir():
                for file in artifact_dir.iterdir():
                    if not file.is_file():
                        continue
                    name = file.name
                    if name.endswith(
                        (
                            ".meta",
                            ".meta.tmp",
                            ".reclaim_tmp",
                            ".pending_delete",
                            ".meta.pending_delete",
                            ".tmp",
                            ".partial",
                            ".backup",
                            ".meta.backup",
                            ".quarantine",
                        )
                    ):
                        continue
                    if artifact_re.match(name):
                        file_path = file.resolve()
                        break
                if file_path is not None:
                    break

        if file_path is None or not file_path.is_file():
            raise FileNotFoundError(f"Artifact not found: {storage_key}")

        meta_path = ReportArtifactStorage._meta_path(file_path)
        meta = ReportArtifactStorage._read_sidecar(meta_path)
        if meta is not None:
            raise PermissionError(
                f"Storage key {storage_key} has owner metadata. "
                f"Use delete() with correct claim_token/version instead."
            )

        # Compute source hash for audit trail
        source_hash = self._compute_sha256(file_path) if file_path.is_file() else ""

        # Step 1: Insert outbox (status='pending_audit')
        outbox_id = repository.insert_deletion_outbox(
            storage_key=storage_key,
            migration_actor=migration_actor,
            audit_reason=audit_reason,
            operation="legacy_delete",
            source_hash=source_hash,
        )

        # Step 2: Commit -- audit committed before file delete
        repository.commit()

        # Step 3: Perform file deletion (quarantine+rename pattern)
        try:
            pending_file = ReportArtifactStorage._pending_delete_path(file_path)
            file_path.rename(pending_file)
            pending_file.unlink(missing_ok=True)
        except Exception:
            # Step 5 (failure path): update status to delete_failed, commit, then raise
            repository.update_deletion_outbox_status(outbox_id, "delete_failed")
            repository.commit()
            raise

        # Step 4: Update outbox status to 'audited' on success
        repository.update_deletion_outbox_status(outbox_id, "audited")

        # Step 5: Commit again
        repository.commit()

    def _write_audit_log(
        self,
        *,
        storage_key: str,
        migration_actor: str,
        audit_reason: str,
        operation: str = "legacy_delete",
        result: str,
        source_hash: str | None = None,
    ) -> None:
        """Write a persistent audit log entry as a JSON file.

        Audit records are stored in ``<base_dir>/.audit_logs/<uuid>.json``
        so they survive filesystem reboots and are independent of any
        database connection.
        """
        audit_dir = self._base_dir / ".audit_logs"
        audit_dir.mkdir(parents=True, exist_ok=True)
        entry = {
            "id": str(uuid.uuid4()),
            "storage_key": storage_key,
            "migration_actor": migration_actor,
            "audit_reason": audit_reason,
            "operation": operation,
            "result": result,
            "source_hash": source_hash or "",
            "created_at": datetime.now(UTC).isoformat(),
        }
        audit_path = audit_dir / f"{entry['id']}.json"
        audit_path.write_text(json.dumps(entry, sort_keys=True, ensure_ascii=False))

    def cleanup_temp(self, temp_path: str) -> None:
        """Delete a temp file (best-effort, no error if missing).

        Parameters
        ----------
        temp_path:
            Path to the temp file to delete.
        """
        import contextlib

        with contextlib.suppress(Exception):
            Path(temp_path).unlink(missing_ok=True)
