"""Local filesystem artifact storage adapter.

Stores report export artifacts on the local filesystem with SHA-256
verification.  Storage keys are UUID-based and generated by the system
(not user-provided) to prevent path traversal.
"""

from __future__ import annotations

import hashlib
import os
import re
import uuid
from pathlib import Path

from cold_storage.modules.reports.domain.errors import PathTraversalError


def _sanitize_file_name(file_name: str) -> str:
    """Sanitize file name: keep only alphanumeric, dash, underscore, dot."""
    # Remove path components
    base = os.path.basename(file_name)
    # Replace special characters with underscore
    sanitized = re.sub(r"[^a-zA-Z0-9._-]", "_", base)
    # Collapse multiple underscores
    sanitized = re.sub(r"_+", "_", sanitized)
    # Strip leading/trailing underscores and dots
    sanitized = sanitized.strip("_.")
    return sanitized or "artifact"


def _validate_storage_key(key: str) -> None:
    """Validate storage key has no path traversal characters."""
    if ".." in key or "/" in key or "\\" in key:
        raise PathTraversalError(key)
    if not key:
        raise PathTraversalError(key)


class ReportArtifactStorage:
    """Local filesystem artifact storage adapter.

    Parameters
    ----------
    base_dir:
        Root directory for artifact storage.  Created on init if missing.
    """

    def __init__(self, base_dir: str) -> None:
        self._base_dir = Path(base_dir)
        self._base_dir.mkdir(parents=True, exist_ok=True)

    def put(self, artifact_id: str, data: bytes, file_name: str) -> str:
        """Store artifact data and return a storage key.

        Parameters
        ----------
        artifact_id:
            The artifact UUID (used for directory structure).
        data:
            Raw file bytes to store.
        file_name:
            Original file name (will be sanitized).

        Returns
        -------
        str
            Storage key (UUID-based) for later retrieval.

        Raises
        ------
        ValueError
            If data is empty or file_name is invalid after sanitization.
        """
        if not data:
            raise ValueError("Artifact data must not be empty")

        storage_key = str(uuid.uuid4())
        safe_name = _sanitize_file_name(file_name)
        artifact_dir = self._base_dir / artifact_id
        artifact_dir.mkdir(parents=True, exist_ok=True)
        file_path = artifact_dir / f"{storage_key}_{safe_name}"

        # Write data
        file_path.write_bytes(data)

        # SHA-256 verification after write
        actual_hash = self._compute_sha256(file_path)
        expected_hash = hashlib.sha256(data).hexdigest()
        if actual_hash != expected_hash:
            # Clean up on verification failure
            file_path.unlink(missing_ok=True)
            raise ValueError(
                f"SHA-256 verification failed: expected {expected_hash}, got {actual_hash}"
            )

        return storage_key

    def get(self, storage_key: str) -> bytes:
        """Retrieve artifact data by storage key.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.

        Returns
        -------
        bytes
            The raw file content.

        Raises
        ------
        FileNotFoundError
            If the artifact does not exist.
        """
        path = self.get_path(storage_key)
        return Path(path).read_bytes()

    def exists(self, storage_key: str) -> bool:
        """Check if an artifact exists.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.

        Returns
        -------
        bool
            True if the artifact file exists.
        """
        try:
            path = self.get_path(storage_key)
            return Path(path).is_file()
        except (PathTraversalError, FileNotFoundError):
            return False

    def delete(self, storage_key: str) -> None:
        """Delete an artifact.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.

        Raises
        ------
        FileNotFoundError
            If the artifact does not exist.
        """
        path = self.get_path(storage_key)
        file_path = Path(path)
        if not file_path.is_file():
            raise FileNotFoundError(f"Artifact not found: {storage_key}")
        file_path.unlink()

    def get_path(self, storage_key: str) -> str:
        """Get the absolute path for an artifact.

        Parameters
        ----------
        storage_key:
            The UUID-based storage key.

        Returns
        -------
        str
            Absolute file path.

        Raises
        ------
        PathTraversalError
            If the storage key contains traversal characters.
        FileNotFoundError
            If the artifact does not exist.
        """
        _validate_storage_key(storage_key)

        # Search for the file in artifact subdirectories
        for artifact_dir in self._base_dir.iterdir():
            if artifact_dir.is_dir():
                for file in artifact_dir.iterdir():
                    if file.is_file() and file.name.startswith(storage_key):
                        return str(file.resolve())

        raise FileNotFoundError(f"Artifact not found: {storage_key}")

    @staticmethod
    def _compute_sha256(file_path: Path) -> str:
        """Compute SHA-256 hash of a file."""
        sha256 = hashlib.sha256()
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                sha256.update(chunk)
        return sha256.hexdigest()
