"""Public project read-model entry point for V2.0 factory-power presentation."""

from cold_storage.modules.calculations.application.factory_power_presentation import (
    DETAIL_DISPLAY_LABELS,
    FACTORY_POWER_CALCULATOR_ID,
    FACTORY_POWER_CALCULATOR_IDENTITY,
    FACTORY_POWER_CALCULATOR_VERSION,
    FACTORY_POWER_DETAIL_FIELDS,
    FACTORY_POWER_RESULT_KIND,
    FACTORY_POWER_RESULT_SCHEMA_VERSION,
    FACTORY_POWER_SUMMARY_FIELDS,
    FACTORY_POWER_UNAVAILABLE_CODE,
    POOL_DISPLAY_LABELS,
    FactoryPowerPresentation,
    FactoryPowerPresentationError,
    attach_factory_power_presentation,
    build_factory_power_presentation,
    canonical_result_hash,
    factory_power_presentation_from_record,
    factory_power_presentation_from_records,
    is_factory_power_record,
    select_latest_factory_power_record,
)

__all__ = [
    "DETAIL_DISPLAY_LABELS",
    "FACTORY_POWER_CALCULATOR_ID",
    "FACTORY_POWER_CALCULATOR_IDENTITY",
    "FACTORY_POWER_CALCULATOR_VERSION",
    "FACTORY_POWER_DETAIL_FIELDS",
    "FACTORY_POWER_RESULT_KIND",
    "FACTORY_POWER_RESULT_SCHEMA_VERSION",
    "FACTORY_POWER_SUMMARY_FIELDS",
    "FACTORY_POWER_UNAVAILABLE_CODE",
    "POOL_DISPLAY_LABELS",
    "FactoryPowerPresentation",
    "FactoryPowerPresentationError",
    "attach_factory_power_presentation",
    "build_factory_power_presentation",
    "canonical_result_hash",
    "factory_power_presentation_from_record",
    "factory_power_presentation_from_records",
    "is_factory_power_record",
    "select_latest_factory_power_record",
]
