"""Chinese (Simplified) translation catalog.

All message keys are stable contracts — the key itself is the stable identifier,
not the Chinese text.  Missing keys cause ``MissingTranslationError``.
"""

from __future__ import annotations

from types import MappingProxyType

_MESSAGES: dict[str, str] = {
    # ── Report titles ──
    "report.title": "冷链物流规划报告",
    "report.subtitle": "冷链仓储规划概念设计报告",
    "report_type.cold_storage_concept_design": "概念设计报告",
    # ── Section headings ──
    "section.report_metadata": "报告元数据",
    "section.project_summary": "项目概况",
    "section.design_basis": "设计依据",
    "section.input_conditions": "输入条件",
    "section.assumptions": "假设条件",
    "section.throughput_inventory_area": "吞吐、库存与面积",
    "section.cooling_load": "冷负荷计算",
    "section.equipment_selection": "设备选型",
    "section.electrical_and_energy": "电气及能耗",
    "section.scheme_comparison": "方案比较",
    "section.investment_estimate": "投资估算",
    "section.risks_and_missing_information": "风险与缺失信息",
    "section.quality_summary": "质量摘要",
    "section.citations": "引用信息",
    "section.citations_and_approval": "引用与审批",
    "section.provenance": "出处信息",
    # ── Document control ──
    "document_control.title": "文件控制信息",
    "document_control.content_hash": "内容哈希",
    "document_control.template_version": "模板版本",
    "document_control.generated_by": "生成者",
    "document_control.generated_at": "生成时间",
    "document_control.revision": "修订号",
    # ── Cover ──
    "cover.version_line": "版本 {number}  |  {date}",
    # ── Field labels ──
    "field.project_name": "项目名称",
    "field.project_location": "项目地点",
    "field.description": "项目描述",
    "field.project_id": "项目编号",
    "field.project_version_id": "项目版本号",
    "field.report_id": "报告编号",
    "field.schema_version": "Schema版本",
    "field.report_type": "报告类型",
    "field.revision_number": "修订编号",
    "field.generated_at": "生成时间",
    "field.generated_by": "生成者",
    "field.total_capital_cost": "总投资",
    "field.annual_energy_cost": "年能耗费用",
    "field.total_cost_10yr": "10年总成本",
    "field.equipment_count": "设备台数",
    "field.total_power": "总功率",
    "field.cop_system": "系统COP",
    "field.payback_years": "回收期",
    "field.npv_10yr": "10年NPV",
    "field.co2_emissions": "CO₂排放",
    "field.total_findings": "总发现数",
    "field.blocker_count": "阻断项数",
    "field.warning_count": "警告项数",
    "field.info_count": "信息项数",
    "field.recommended_scheme": "推荐方案",
    "field.total_design_refrigeration_load": "总设计制冷量",
    "field.rank": "排名",
    # ── New field keys for rich provider ──
    "field.total_compressor_capacity": "总压缩机容量",
    "field.total_installed_power": "总装机功率",
    "field.daily_inbound_mass_kg": "日入库质量",
    "field.storage_capacity_kg": "存储容量",
    "field.total_area_m2": "总面积",
    "field.condenser_heat_rejection": "冷凝器排热量",
    # ── Provenance fields ──
    "field.content_hash": "内容哈希",
    "field.canonical_hash": "规范哈希",
    "field.selection_rules": "选择规则",
    "field.assembly_timestamp": "组装时间戳",
    "field.run_id": "运行ID",
    "field.generator_version": "生成器版本",
    "field.scheme_evaluator": "方案评估器",
    "field.persisted_content_hash": "持久化内容哈希",
    # ── Scheme comparison table headers ──
    "header.scheme": "方案",
    "header.scheme_comparison": "方案比较",
    "header.scheme_name": "方案名称",
    "header.recommended": "推荐",
    "header.rank": "排名",
    "header.scheme_id": "方案ID",
    "header.total_score": "综合评分",
    "header.total_investment_cny": "总投资(CNY)",
    "header.total_area_m2": "总面积(m²)",
    "header.total_capital_cost": "总投资",
    "header.equipment": "设备",
    "header.construction": "土建",
    "header.civil_works": "土建工程",
    "header.refrigeration_system": "制冷系统",
    "header.electrical_system": "电气系统",
    "header.other_costs": "其他费用",
    "header.breakdown_item": "项目",
    "header.amount": "金额",
    "header.cooling_capacity": "制冷量",
    "header.power_consumption": "耗电量",
    "header.annual_throughput": "年吞吐量",
    "header.storage_capacity": "存储容量",
    "header.room_area": "房间面积",
    "header.unit_price": "单价",
    "header.quantity": "数量",
    "header.total": "合计",
    "header.risks_items": "风险项",
    "header.mitigation": "缓解措施",
    "header.missing_information": "缺失信息",
    "header.impact": "影响",
    "header.annual_energy_cost": "年能耗费用",
    "header.total_cost_10yr": "10年总成本",
    "header.equipment_count": "设备台数",
    "header.total_power": "总功率",
    "header.cop_system": "系统COP",
    "header.payback_years": "回收期",
    "header.npv_10yr": "10年NPV",
    "header.co2_emissions": "CO₂排放",
    "header.operating_cost_per_year": "年运行费用",
    "header.design_cooling_load_kw_r": "设计冷负荷(kW(r))",
    "header.installed_power_kw_e": "装机功率(kW(e))",
    # ── Risk / quality table headers ──
    "header.code": "代码",
    "header.severity": "严重性",
    "header.message": "消息",
    "header.source": "来源",
    "header.quality_findings": "质量发现",
    # ── Citation table headers ──
    "header.section": "节",
    "header.source_type": "来源类型",
    "header.source_id": "来源ID",
    "header.tool": "工具",
    "header.content_hash": "内容哈希",
    "header.citation_sources": "引用来源",
    # ── Risk / quality labels ──
    "label.risks_items": "风险项：",
    "label.mitigation": "缓解措施：",
    "label.missing_information": "缺失信息：",
    "label.impact": "影响：",
    "label.quality_summary": (
        "质量摘要：共 {total} 项发现：{blocker_count} 个阻断项、"
        "{warning_count} 个警告、{info_count} 个提示"
    ),
    "label.recommended_scheme": "推荐方案：{scheme}",
    # ── Approval labels ──
    "label.approval_info": "审批信息：",
    "label.approved_revision_number": "批准修订号：{value}",
    "label.approved_by": "批准人：{value}",
    "label.approved_at": "批准时间：{value}",
    "label.approved_revision_id": "批准修订ID：{value}",
    "label.approved_content_hash": "批准内容哈希：{value}",
    # ── Severity ──
    "severity.info": "信息",
    "severity.warning": "警告",
    "severity.blocker": "阻断",
    "severity.medium": "中",
    "severity.high": "高",
    "severity.not_calculated": "未计算",
    "severity.not_provided": "未提供",
    # ── Source type ──
    "source_type.calculation": "计算",
    "source_type.calculation_result": "计算结果",
    "source_type.demo": "演示",
    "source_type.user_input": "用户输入",
    "source_type.project": "项目",
    "source_type.project_version": "项目版本",
    "source_type.agent_session": "Agent会话",
    "source_type.agent_turn": "Agent轮次",
    "source_type.agent_tool_call": "Agent工具调用",
    "source_type.scheme_result": "方案结果",
    "source_type.knowledge_revision": "知识版本",
    # ── Status ──
    "status.draft": "草稿",
    "status.generated": "已生成",
    "status.under_review": "审核中",
    "status.reviewed": "已审核",
    "status.approved": "已批准",
    "status.archived": "已归档",
    # ── Artifacts ──
    "artifact.pending": "待处理",
    "artifact.rendering": "渲染中",
    "artifact.completed": "已完成",
    "artifact.failed": "失败",
    # ── Render modes ──
    "render_mode.draft": "草稿模式",
    "render_mode.formal": "正式模式",
    # ── Empty sections ──
    "empty.not_provided": "未提供",
    "empty.not_calculated": "未计算",
    # ── Table headers ──
    "table.no_data": "暂无数据",
    # ── Headers and footers ──
    "header.confidentiality": "机密文件 — 仅供内部使用",
    "footer.page": "第 {current} 页 / 共 {total} 页",
    # ── Watermark ──
    "watermark.draft": "草稿",
    # ── Disclaimer ──
    "disclaimer.standard": "AI辅助，仅供参考。",
    # ── Date/time format labels ──
    "datetime.format": "YYYY年MM月DD日 HH:mm",
    # ── Boolean / enum / missing ──
    "bool.yes": "是",
    "bool.no": "否",
    "value.missing": "—",
    # ── Provenance ──
    "provenance.source": "数据来源",
    "provenance.tool": "生成工具",
    "provenance.version": "版本",
    "provenance.content_hash": "内容哈希",
    # ── Export formats ──
    "format.docx": "Word文档",
    "format.pdf": "PDF文档",
    # ── Format helpers ──
    "format.label_value": "{label}：{value}",
    "format.list_item": "• {value}",
    "format.mitigation_suffix": " — 缓解措施：{value}",
    "format.impact_suffix": " — 影响：{value}",
    "format.scheme_comparison": "方案比较",
    "format.recommended_scheme": "推荐方案：{scheme}",
    # ── Investment breakdown labels ──
    "investment.equipment": "设备",
    "investment.construction": "土建",
    "investment.civil_works": "土建工程",
    "investment.refrigeration_system": "制冷系统",
    "investment.electrical_system": "电气系统",
    "investment.other_costs": "其他费用",
    "investment.installation": "安装",
    "investment.design": "设计",
    "investment.commissioning": "调试",
    # ── Impact labels ──
    "impact.not_provided": "未提供",
    "impact.not_calculated": "未计算",
    "impact.foundation_design": "基础设计",
    "impact.significant": "影响显著",
    "impact.minor": "影响较小",
    # ── Units (display labels, not values) ──
    "unit.kw_r": "kW(r)",
    "unit.kw_e": "kW(e)",
    "unit.kw_th": "kW(th)",
    "unit.kwh": "kWh",
    "unit.m2": "m²",
    "unit.cny": "元",
    "unit.kg": "kg",
    "unit.count": "个",
    "unit.pallet": "托盘",
    "unit.score": "分",
}

# Immutable mapping — runtime cannot modify catalog messages
MESSAGES: MappingProxyType[str, str] = MappingProxyType(_MESSAGES)
